// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// Generated by studio/scripts/generate-builtin-behaviors.mjs

import type { BehaviorType } from "../types";

export interface BuiltinBehaviorCatalogItem {
  src: string;
  type: BehaviorType;
  descriptionKey: string;
  descriptionFallback: string;
}

export const BUILTIN_BEHAVIOR_CATALOG =
[
  {
    "src": "builtin:action:logBasicInfo",
    "type": "action",
    "descriptionKey": "defaults.registry.logBasicInfo.description",
    "descriptionFallback": "Logs basic event and execution context information."
  },
  {
    "src": "builtin:action:logArgs",
    "type": "action",
    "descriptionKey": "defaults.registry.logArgs.description",
    "descriptionFallback": "Logs arguments to console."
  },
  {
    "src": "builtin:action:logArgsWithoutKeys",
    "type": "action",
    "descriptionKey": "defaults.registry.logArgsWithoutKeys.description",
    "descriptionFallback": "Logs argument values omitting object keys."
  },
  {
    "src": "builtin:action:logJustArgsValues",
    "type": "action",
    "descriptionKey": "defaults.registry.logJustArgsValues.description",
    "descriptionFallback": "Logs only argument values in order."
  },
  {
    "src": "builtin:observer:containsAllEvents",
    "type": "observer",
    "descriptionKey": "defaults.registry.containsAllEvents.description",
    "descriptionFallback": "Evaluates if all required events have arrived."
  },
  {
    "src": "builtin:observer:containsAtLeastOneEvent",
    "type": "observer",
    "descriptionKey": "defaults.registry.containsAtLeastOneEvent.description",
    "descriptionFallback": "Evaluates if at least one required event has arrived."
  },
  {
    "src": "builtin:observer:alwaysTrue",
    "type": "observer",
    "descriptionKey": "defaults.registry.alwaysTrue.description",
    "descriptionFallback": "Always approves execution."
  },
  {
    "src": "builtin:observer:greaterThanEqualCounter",
    "type": "observer",
    "descriptionKey": "defaults.registry.greaterThanEqualCounter.description",
    "descriptionFallback": "Approves when event counter is greater than or equal to the configured minimum."
  },
  {
    "src": "builtin:observer:totalEventsBetweenLimits",
    "type": "observer",
    "descriptionKey": "defaults.registry.totalEventsBetweenLimits.description",
    "descriptionFallback": "Approves when total events are within configured limits."
  }
] as const satisfies ReadonlyArray<BuiltinBehaviorCatalogItem>;
